const hotels = [
  'Aria',
  'Artisan Hotel',
  `Bally's`,
  'Bellagio',
  'California Hotel',
  'Casino Royale',
  'Caesars Palace',
  'Circus Circus',
  'Cosmopolitan',
  'Delano',
  'Downtown Grand',
  'El Cortez',
  'Ellis Island',
  'Encore',
  'Excalibur',
  'Flamingo',
  'Fortune Hotel',
  'Four Queens',
  'Four Seasons',
  'Gold Coast',
  'Golden Gate Hotel',
  'Golden Nugget',
  'Hard Rock',
  `Harrah's`,
  'Hooters',
  'Luxor',
  'Main Street Station',
  'Mandalay Bay',
  'MGM Grand',
  'MGM Signature',
  'Mirage',
  'Montecarlo',
  'Nobu Hotel',
  'NoMad',
  'Oasis at Gold Spike',
  'Orleans',
  'Palace Station',
  'Palazzo',
  'Palms',
  'Palms Place',
  'Paris',
  'Park MGM',
  'Planet Hollywood',
  'Plaza',
  'Rennaisance Las Vegas',
  'Rio',
  'SLS Las Vegas',
  'Stratosphere',
  'The Cromwell',
  'The D',
  'The Linq',
  'Treasure Island',
  'Tropicana',
  'Trump',
  'Tuscany Suites',
  'Vdara',
  'Venetian',
  'Waldorf Astoria',
  'Westgate',
  'Westin Las Vegas',
];

export default hotels;
