const hotels = [
  'Aria',
  'Artisan Hotel',
  `Bally's`,
  'Bellagio',
  'California Hotel',
  'Casino Royale',
  'Caesars Palace',
  'Circus Circus',
  'Cosmopolitan',
  'Courtyard by Marriot',
  'Delano',
  'Downtown Grand',
  'El Cortez',
  'Elara by Hilton',
  'Ellis Island',
  'Embassy Suites',
  'Encore',
  'Excalibur',
  'Flamingo',
  'Fortune Hotel',
  'Four Queens',
  'Four Seasons',
  'Gold Coast',
  'Golden Gate Hotel',
  'Golden Nugget',
  'Hard Rock',
  `Harrah's`,
  'Hilton Grand Vacations (LV Convention Center)',
  'Hilton Grand Vacations on the Strip',
  'Hilton Grand Vacations at the Flamingo',
  'Hooters',
  'Las Vegas Marriot',
  'Luxor',
  'Main Street Station',
  'Mandalay Bay',
  'MGM Grand',
  'MGM Signature',
  'Mirage',
  'Montecarlo',
  'Nobu Hotel',
  'NoMad',
  'Oasis at Gold Spike',
  'Orleans',
  'Palace Station',
  'Palazzo',
  'Palms',
  'Palms Place',
  'Paris',
  'Park MGM',
  'Planet Hollywood',
  'Plaza',
  'PE Hotel',
  'Rennaisance Las Vegas',
  'Residence Inn by Marriot (LV Convention Center)',
  'Rio',
  'SLS Las Vegas',
  'Springhill Suites',
  'Stratosphere',
  'The Cromwell',
  'The D',
  'The Linq',
  'Treasure Island',
  'Tropicana',
  'Trump',
  'Tuscany Suites',
  'Vdara',
  'Venetian',
  'Waldorf Astoria',
  'Westgate',
  'Westin Las Vegas',
];

export default hotels;
