const unsortedHotels = [
  'Aria',
  'Artisan Hotel',
  `Bally's`,
  'Bellagio',
  'California Hotel',
  'Casino Royale',
  'Caesars Palace',
  'Circus Circus',
  'Cosmopolitan',
  'Courtyard by Marriot (LV Convention Center)',
  'Courtyard by Marriot (LV South)',
  'Delano',
  'Downtown Grand',
  'El Cortez',
  'Elara by Hilton Grand Vacations',
  'Ellis Island',
  'Embassy Suites (LV Convention Center)',
  'Encore',
  'Excalibur',
  'Fairfield Inn by Marriot (LV South)',
  'Flamingo',
  'Fortune Hotel',
  'Four Queens',
  'Four Seasons',
  'Gold Coast',
  'Golden Gate Hotel',
  'Golden Nugget',
  'Hard Rock',
  `Harrah's`,
  'Hilton Garden Inn - City Center',
  'Hilton Grand Vacations (LV Convention Center)',
  'Hilton Grand Vacations on the Strip',
  'Hilton Grand Vacations at the Flamingo',
  'Home2 Suites - Tropicana',
  'Homewood Suites by Hilton - City Center',
  'Hooters',
  'Las Vegas Marriot',
  'Luxor',
  'Main Street Station',
  'Mandalay Bay',
  'MGM Grand',
  'MGM Signature',
  'Mirage',
  'Montecarlo',
  'Nobu Hotel',
  'NoMad',
  'Oasis at Gold Spike',
  'Orleans',
  'Palace Station',
  'Palazzo',
  'Palms',
  'Palms Place',
  'Paris',
  'Park MGM',
  'Planet Hollywood',
  'Plaza',
  'PE Hotel',
  'Rennaisance Las Vegas',
  'Residence Inn by Marriot (LV Convention Center)',
  'Residence Inn by Marriot (LV South)',
  'Rio',
  'SLS Las Vegas',
  'Springhill Suites',
  'Staybridge Suites',
  'Stratosphere',
  'The Cromwell',
  'The D',
  'The Linq',
  'TownePlace Suites (Tropicana)',
  'Treasure Island',
  'Tropicana',
  'Trump',
  'Tuscany Suites',
  'Vdara',
  'Venetian',
  'Waldorf Astoria',
  'Westgate',
  'Westin Las Vegas',
];

const hotels = unsortedHotels.sort();
export default hotels;
